server:
  #指定服务端口
  port: 9527
spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      # 表示eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后server端没收到client的心跳，则摘除该instance。默认30s
      #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，如果要迅速获取服务注册状态，可以缩小该值
      lease-renewal-interval-in-seconds: 5
      # 表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。默认90s
        # 如果该值太大，则很可能将流量转发过去的时候，该instance已经不存活了。
      # 如果该值设置太小了，则instance则很可能因为临时的网络抖动而被摘除掉。
      # 该值至少应该大于 leaseRenewalIntervalInSeconds
      lease-expiration-duration-in-seconds: 10
      defaultZone: http://localhost:9900/eureka/
  instance:
    instance-id: zuul-9527
    prefer-ip-address: true

#zuul:
#  routes: # 隐藏真实的服务名   以后都用9527统一对外提供接口    localhost:9527/mymenu/menu/getPort
#    mymenu.serviceId: menu
#    mymenu.path: /mymenu/**   # 相当于所有的微服务前都加了一个前缀
#
#    myclient.serviceId: client
#    myclient.path: /**   # 访问localhost:9527/login.html正常 但是登录404(localhost:9527/account/login)
#
#    eureka-feign:
#      serviceId: client # 对应服务名称
#      path: /**
#  ignored-services: menu, user # 真实的按照服务名路径不能访问了   localhost:9527/menu/menu/getPort   第一个menu是微服务名，第二个是requestmapping

